export const ACTION_LOAD_CURRENCY_PAIR_LIST = 'ACTION_LOAD_CURRENCY_PAIR_LIST';

export const ACTION_LOAD_CURRENCY_PAIR = 'ACTION_LOAD_CURRENCY_PAIR';

export const ACTION_START = 'ACTION_START';
export const ACTION_SUCCESS = 'ACTION_SUCCESS';
export const ACTION_FAIL = 'ACTION_FAIL';
export const ACTION_CHANGE_ACTIVE = 'ACTION_CHANGE_ACTIVE';